spring:
  rabbitmq:
    ####连接地址
    host: 119.29.75.165
    ####端口号
    port: 5672
    ####账号
    username: ponderyao
    ####密码
    password: 103123Yzp
    ### 地址
    virtual-host: /transaction_distributed
    listener:
      simple:
        retry:
          ####开启消费者（程序出现异常的情况下会）进行重试
          enabled: true
          ####最大重试次数
          max-attempts: 5
          ####重试间隔次数
          initial-interval: 3000
        ####开启手动ack
        acknowledge-mode: manual

  #数据库连接信息
  datasource:
    name: webserver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/webserver?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 103123Yzp
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8081

